### ISSUE TITLE
If you installed before 15-Nov-2024 may need to uninstall / reinstall 

### ISSUE THREAD

**Issue by thejoester** [thejoester/pf2e-alchemist-remaster-ducttape#1]
Still learning with modules and Github, the links I had in module.json were not pointing to the latest release. Sorry about that.

**Comment by Armandeus66** [comment]
I'm getting a message to update the link every time I update modules, and clicking yes does not stop it from appearing again.
![Uploading Screenshot 2024-11-17 141312.png…]()
