### ISSUE TITLE
Powerful Alchemy error

### ISSUE THREAD

**Issue by Suldrun45** [thejoester/pf2e-alchemist-remaster-ducttape#10]
There is an error in PowerfulAlchemy.js preventing the update of the DC in the description:
In the `updateDescription` function, on line 18, `const itemName = item.name;` 
![image](https://github.com/user-attachments/assets/a9d499fb-5290-4dba-8867-10274f378d72)

**Comment by thejoester** [comment]
took a quick peek and spotted the issue right away. Fixed in [Release 2.5.1](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.5.1)
