### ISSUE TITLE
Selected Character is not an Alchemist!

### ISSUE THREAD

**Issue by sonofkyusss** [thejoester/pf2e-alchemist-remaster-ducttape#13]
Hi,
I get this when a alchemist character uses the macro (GM & Player) :
"Selected Character is not an Alchemist!"
I get multiple ones when creating a new PC alchemist.

Forge v12.331 & Pf2e v6.8.0
Plus Babele translation

(thanks for the mod, my alchemist player LOVES it!)

**Comment by thejoester** [comment]
Thanks!! I hope to have this fixed tonight or tomorrow.

**Comment by thejoester** [comment]
fixed in [Release 2.5.3](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.5.2)
