### ISSUE TITLE
Alchemist caracter ignored

### ISSUE THREAD

**Issue by sonofkyusss** [thejoester/pf2e-alchemist-remaster-ducttape#14]
Hi,

Me again, I didn't mention that the macro wasn't launching in my last bug report.
Now the the message is not displaying outside of the console but still ignores alchemist caracter (and won't launch).

![image](https://github.com/user-attachments/assets/4e10f102-69a9-46e1-b3ac-e42b7ea43010)

Foundry v12.331 & Patfinder2e v6.8.0

**Comment by thejoester** [comment]
can you export your character to a .json file (in actors tab right click on your character and choose "export data". Save the file and attach it here? 

I think what is happening is I am checking for `actor?.class?.name?.toLowerCase() === "alchemist";` but other languages will be different so I will need to use the localization. I am hoping if you export your character it will let me test.

**Comment by thejoester** [comment]
Issue should be fixed in [Release 2.5.3](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.5.3). I changed to checking by slug. 

Please test and let me know.

**Comment by sonofkyusss** [comment]
It works again !
Thanks
