### ISSUE TITLE
Search Formulas

### ISSUE THREAD

**Issue by tpendragon** [thejoester/pf2e-alchemist-remaster-ducttape#4]
Hi! Love this module as a workaround for existing functionality. I recently tried to implement searching of formulas for Advanced Alchemy for alchemists in https://github.com/foundryvtt/pf2e/pull/17558, but they're not looking at crafting patches right now. Do you think we could get that kind of thing implemented here somehow?

**Comment by thejoester** [comment]
Thanks!

I would be willing to give it a try. Tell me what exactly your goal would be? Add a search/filter text box to the forumulas page or would a pop-up window work as well?

**Comment by tpendragon** [comment]
Either would be fine, as long as you can drag the results to advanced alchemy.

**Comment by thejoester** [comment]
> Either would be fine, as long as you can drag the results to advanced alchemy.

How does this look? 

![Formula Search example](https://i.ibb.co/6PSD5zJ/search-formulas.gif)

**Comment by tpendragon** [comment]
@thejoester Amazing, exactly what I need.

**Comment by thejoester** [comment]
implemented in [2.2.0](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.2.0)
