### ISSUE TITLE
The macro doesn't seem to work on characters with lots of formulas (or higher level)

### ISSUE THREAD

**Issue by Bomberman1988** [thejoester/pf2e-alchemist-remaster-ducttape#5]
It works fine with lower level Alchies, but I have a lv12 Toxicologist and a lv9 Bomber, the macro doesn't seem to work with them, I waited a long time, tried multiple times but it just doesn't work. 

PS: my characters and their feats are all up to date (I also use the Revitalizer module)

**Comment by thejoester** [comment]
> It works fine with lower level Alchies, but I have a lv12 Toxicologist and a lv9 Bomber, the macro doesn't seem to work with them, I waited a long time, tried multiple times but it just doesn't work.
> 
> PS: my characters and their feats are all up to date (I also use the Revitalizer module)

Can you do me a favor? Can you export your character data (Right-Click your character in  the actor tab, then choose export data) and attach the .json file here?

**Comment by thejoester** [comment]
Tested on my end and added over 100 formulas and still had no issues...

**Comment by Bomberman1988** [comment]
[fvtt-Actor-2001-bomberman-yQEpVEL5oaQCRjBP.json](https://github.com/user-attachments/files/18025908/fvtt-Actor-2001-bomberman-yQEpVEL5oaQCRjBP.json)
[fvtt-Actor-2007-yudokuna-kDRuiL8AKEZ46oRF.json](https://github.com/user-attachments/files/18025909/fvtt-Actor-2007-yudokuna-kDRuiL8AKEZ46oRF.json)

Sure! Here they are

**Comment by thejoester** [comment]
Making progress. It seems a few of your formulas are coming back as null when looking them up by uuid. Will need to collect more data to see if I can find out why.

**Comment by thejoester** [comment]
> [fvtt-Actor-2001-bomberman-yQEpVEL5oaQCRjBP.json](https://github.com/user-attachments/files/18025908/fvtt-Actor-2001-bomberman-yQEpVEL5oaQCRjBP.json) [fvtt-Actor-2007-yudokuna-kDRuiL8AKEZ46oRF.json](https://github.com/user-attachments/files/18025909/fvtt-Actor-2007-yudokuna-kDRuiL8AKEZ46oRF.json)
> 
> Sure! Here they are

Pushed release [2.2.1](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.2.1) - this should resolve your issue. Can you test and report back?

**Comment by Bomberman1988** [comment]
It seems to be working now, thank you very much! :D
