### ISSUE TITLE
[Feature Request] Versatile Vial Automation

### ISSUE THREAD

**Issue by ottyn** [thejoester/pf2e-alchemist-remaster-ducttape#6]
With the next release having the remaster Alchemist changes in the PF2e system.  I would love to see this module continue with the automation features you have been implementing, like the auto-add new formulas for known recipes on level up.

One feature I would like to request, if it's possible, is maybe a unlimited duration effect to apply to the Alchemist that can add the 2 versatile vials back per 10 minutes outside of combat (kind of like the Refocus ability).  Thinking an Effect would be the best way to implement since they can interact with the world clock for timing.

**Comment by thejoester** [comment]
Thanks for the feedback and suggestion! I was planning on seeing how they implement the Alchemist and what automatons are done with it, then modifying this module to suit. I may even keep the Quick Alchemy macro if it is still useful. 

I will look into your suggestion. Not sure if an effect would be necessary, if 10 minutes pass in game then maybe prompt in chat for that player?

**Comment by ottyn** [comment]
> Thanks for the feedback and suggestion! I was planning on seeing how they implement the Alchemist and what automatons are done with it, then modifying this module to suit. I may even keep the Quick Alchemy macro if it is still useful.
> 
> I will look into your suggestion. Not sure if an effect would be necessary, if 10 minutes pass in game then maybe prompt in chat for that player?

Yeah that might work also.  Just some kind of reminder for the player that they need to increase their Versatile Vials if they aren't at max already.

**Comment by thejoester** [comment]
I have this working I believe. Just wanna test it a little more before I push it tonight.

**Comment by thejoester** [comment]
Implemented with [Release 2.4.0](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.4.0)
