### ISSUE TITLE
Alchemsts with Alchemical Expertise should be prompted to add 3 vials instead of 2.

### ISSUE THREAD

**Issue by maplealmond** [thejoester/pf2e-alchemist-remaster-ducttape#7]
A level 9 Alchemist has the following

> Constant practice has increased the effectiveness of your concoctions. Your proficiency rank for your alchemist class DC increases to expert. In addition, when you gather reagents during exploration mode, you can regain three vials instead of two.

**Comment by thejoester** [comment]
Implemented in [Release 2.4.1](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.4.1)

**Comment by maplealmond** [comment]
Yay. However I think this introduced a new bug.  It adds to both the number of vials collected and the maximum.  I believe it should only add to the number collected.

**Comment by thejoester** [comment]
Okay, This should be fixed now in [Release 2.4.2](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.4.2)
