### ISSUE TITLE
Issue when using pf2e in another langugage

### ISSUE THREAD

**Issue by Glunty** [thejoester/pf2e-alchemist-remaster-ducttape#8]
Hello,

Thanks for the module, I'm eager to try a solution to ease my alchemist player's work !

I couldn't make the macro run in my world, and I found out it's because I'm using pf2e in another language. So the item with the name "Versatile Vial" does not exist in my compendium, as name are translated. I made it work by hardcoding my translation in VialSearch.addVialsToActor().
I think a nicer solution would be to use slug (or UUID) instead of name, as they are not translated.

![image](https://github.com/user-attachments/assets/a5e400b4-ed04-473a-96d8-fb8dc39755bf)

**Comment by thejoester** [comment]
For now I will add this to settings, to make it easy to overwrite: 

![image](https://github.com/user-attachments/assets/9aad2d06-5239-47f7-b008-5fd979b7799a)

**Comment by thejoester** [comment]
Okay I have fixed this to use the uuid, so name will not matter. Removed setting. 

implemented in [Release 2.4.2](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.4.2)
