### ISSUE TITLE
[Issue] Finding a vial should respect longer timeskips

### ISSUE THREAD

**Issue by maplealmond** [thejoester/pf2e-alchemist-remaster-ducttape#9]
If time skips by 1 hour, the vial finding will only note a 10 minute in exploration mode.  Now that the alchemist cannot multi-click, this means they have to manually add extra.

If skipping 20/30/40 minutes at once, the number of vials found should be multiplied by 2/3/4 etc, up to the maximum limit possible.

**Comment by thejoester** [comment]
I will work on implementing this, will probably still limit it to an hour maybe two, as a full day or long rest will make any vials expire.

**Comment by thejoester** [comment]
Implemented in [Release 2.4.3](https://github.com/thejoester/pf2e-alchemist-remaster-ducttape/releases/tag/2.4.3)
